# -*- coding: utf-8 -*-
"""Kopie von demo_notebook_minimal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10PaQ0dym5AC39IzF5qt768TgWmgl0gVL
"""

seq_fn = r"C:\Users\morit\Downloads\external.seq"
# @title Define tools
import toolapi
from functools import cache

def on_message(msg):
    print(f"\r > {msg}", end="")
    return True

def call(url, **kwargs):
    from time import time
    start = time()
    result = toolapi.call(url, kwargs, on_message)
    print(f"\n --- done ({time() - start:.2f} s) ---")
    return result

# .seq loader: uses disseqt to convert sequence to instant events
def load_seq(path, exact_trajectories=True):
    with open(path) as f:
        file_content = f.read()
    return call(
        "wss://tool-conseq.fly.dev/tool",
        seq_file=file_content,
        exact_trajectory=exact_trajectories
    )

# phantom library: returns rescaled brainweb multi-tissue phantoms (slow)
@cache
def load_phantom(subject, res):
    affine = [
        [2.5, 0.0, 0.0, -90.0],
        [0.0, 2.5, 0.0, -108.75],
        [0.0, 0.0, 2.5, -1.25]
    ]
    return call(
        "wss://tool-phantomlib-flyio.fly.dev/tool",
        subject=subject,  # BrainWeb subject
        res_x=res[0],     # X resolution (1-434)
        res_y=res[1],     # Y resolution (1-362)
        res_z=res[2],     # Z resolution (1-434)
        affine=affine,    # orientation and FOV
    )

# not-yet-quite segmented PDG
def sim_spdg(sequence, phantom):
    return call(
        "wss://tool-rapisim.fly.dev/tool",
        sequence=sequence,
        phantom=phantom,
    )


def sim_mr0(sequence, phantom):
    return call(
        "wss://tool-mr0sim.fly.dev/tool",
        sequence=sequence,
        phantom=phantom,
    )

# @title NIfTI phantom to toolapi conversion code

import json
import re
import tempfile
from pathlib import Path

# NIfTI phantom config next to this script (repo ships brain_default.json, not brain_default_1mm.json)
nifit_json_fn = Path(__file__).resolve().parent / "brain_default_1mm_gz" / "brain_default.json"

import nibabel as nib
import numpy as np
from nibabel.filebasedimages import ImageFileError

from toolapi.value import Volume, PhantomTissue, SegmentedPhantom


def load_phantom_from_nifti(config_path: str | Path) -> SegmentedPhantom:
    """
    Load a NIfTI phantom from a JSON config + NIfTI files on disk and
    convert it into a toolapi SegmentedPhantom.

    Logic matches ``ScanModule._convertResampledGroupToToolPhantom`` in
    ``scan_zero/scan_module.js`` (Pyodide snippet): real voxel data, NIfTI
    affine as the first three rows of the 4×4 matrix, scalar T1/T2/T2′/ADC
    via PD-weighted mean for string file refs, spatially constant dB0 from
    that scalar, and B1 lists only honor numeric entries (string refs are
    skipped; defaults fill empty TX/RX).

    Assumes NIfTI files are already at the desired resolution and affine —
    no resampling is performed.

    Parameters
    ----------
    config_path : path to the phantom JSON config file (e.g. phantom.json)
    """
    config_path = Path(config_path)
    base_dir = config_path.parent

    with open(config_path) as f:
        cfg = json.load(f)

    cache: dict[str, tuple[np.ndarray, np.ndarray]] = {}

    def parse_ref(s: str) -> tuple[str, int]:
        m = re.match(r"^(.+)\[(\d+)\]$", s)
        if not m:
            raise ValueError(f"Invalid ref: {s}")
        return m.group(1), int(m.group(2))

    def load4d(fn: str) -> tuple[np.ndarray, np.ndarray]:
        if fn in cache:
            return cache[fn]
        path = base_dir / fn
        try:
            img = nib.load(str(path))
        except ImageFileError as e:
            if "not a gzip file" in str(e).lower() and str(fn).lower().endswith(".nii.gz"):
                with open(path, "rb") as src, tempfile.NamedTemporaryFile(
                    suffix=".nii", delete=False
                ) as tmp:
                    tmp.write(src.read())
                    tmp_path = tmp.name
                img = nib.load(tmp_path)
            else:
                raise
        dat = img.get_fdata()
        if dat.ndim == 3:
            dat = dat[..., np.newaxis]
        elif dat.ndim != 4:
            raise ValueError(f"Expected 3D or 4D NIfTI, got {dat.ndim}D")
        cache[fn] = (np.asarray(img.affine, dtype=np.float64), dat)
        return cache[fn]

    def make_vol(arr: np.ndarray, aff: np.ndarray) -> Volume:
        return Volume(
            shape=list(arr.shape),
            affine=aff[:3, :4].tolist(),
            data=np.asarray(arr, dtype=np.float64).ravel(order="C").tolist(),
        )

    def _b1_vol_from_array(arr: np.ndarray, aff: np.ndarray) -> Volume:
        v = make_vol(arr, aff)
        v.data = [complex(float(x), 0.0) for x in v.data]
        return v

    tissue_configs = cfg.get("tissues", {})
    tissue_cfg_values = list(tissue_configs.values())
    tissues: dict[str, PhantomTissue] = {}
    first_tissue_config: dict | None = None
    dens_last: np.ndarray | None = None
    aff_last: np.ndarray | None = None

    for _name, t in tissue_configs.items():
        if first_tissue_config is None:
            first_tissue_config = t

        dfn, didx = parse_ref(t["density"])
        aff, d4 = load4d(dfn)
        dens = np.asarray(d4[:, :, :, didx], dtype=np.float64)
        dens_last = dens
        aff_last = aff

        def prop(k: str, default: float) -> float:
            p = t.get(k, default)
            if isinstance(p, (int, float)):
                return float(p)
            if isinstance(p, str):
                fn, idx = parse_ref(p)
                _, v4 = load4d(fn)
                vv = np.asarray(v4[:, :, :, idx], dtype=np.float64).ravel(order="C")
                dd = dens.ravel(order="C")
                s = float(dd.sum())
                return float((dd * vv).sum() / s) if s > 0 else float(default)
            return float(default)

        tissues[_name] = PhantomTissue(
            density=make_vol(dens, aff),
            db0=make_vol(np.ones_like(dens, dtype=np.float64) * prop("dB0", 1.0), aff),
            t1=prop("T1", float("inf")),
            t2=prop("T2", float("inf")),
            t2dash=prop("T2'", float("inf")),
            adc=prop("ADC", 0.0),
        )

    if dens_last is None or aff_last is None:
        raise ValueError("Phantom JSON has no tissues")

    def _first_nonempty_b1(key: str):
        for tt in tissue_cfg_values:
            if not isinstance(tt, dict):
                continue
            vals = tt.get(key, None)
            if isinstance(vals, list) and len(vals) > 0:
                return vals
        return None

    tx_vals = _first_nonempty_b1("B1+")
    rx_vals = _first_nonempty_b1("B1-")
    if tx_vals is None and first_tissue_config:
        tx_vals = first_tissue_config.get("B1+", [1.0])
    if rx_vals is None and first_tissue_config:
        rx_vals = first_tissue_config.get("B1-", [1.0])

    b1_tx: list[Volume] = []
    b1_rx: list[Volume] = []
    for p in tx_vals or [1.0]:
        if isinstance(p, (int, float)):
            arr = np.ones_like(dens_last, dtype=np.float64) * float(p)
            b1_tx.append(_b1_vol_from_array(arr, aff_last))
    for p in rx_vals or [1.0]:
        if isinstance(p, (int, float)):
            arr = np.ones_like(dens_last, dtype=np.float64) * float(p)
            b1_rx.append(_b1_vol_from_array(arr, aff_last))

    if len(b1_tx) == 0:
        b1_tx.append(
            _b1_vol_from_array(np.ones_like(dens_last, dtype=np.float64), aff_last)
        )
    if len(b1_rx) == 0:
        b1_rx.append(
            _b1_vol_from_array(np.ones_like(dens_last, dtype=np.float64), aff_last)
        )

    return SegmentedPhantom(tissues=tissues, b1_tx=b1_tx, b1_rx=b1_rx)

# @title **load .seq + load phantom + run sim** |  _with tools hosted on fly.io_
import matplotlib.pyplot as plt

def _to_complex_np(sig):
    """Convert tool output to np.complex64 array."""
    arr = np.asarray(sig)
    if np.iscomplexobj(arr):
        return arr.astype(np.complex64).ravel()
    if arr.ndim >= 2 and arr.shape[-1] >= 2:
        return (arr[..., 0].astype(np.float32) + 1j * arr[..., 1].astype(np.float32)).ravel()
    if arr.ndim == 1:
        out = []
        for x in arr:
            if isinstance(x, complex):
                out.append(x)
            elif isinstance(x, (list, tuple)) and len(x) >= 2:
                out.append(complex(float(x[0]), float(x[1])))
        if out:
            return np.asarray(out, dtype=np.complex64).ravel()
    raise ValueError(f"Unsupported signal format: shape={arr.shape}, dtype={arr.dtype}")


# ========================
# DIESER CODE IST WICHTIG:
# ========================

seq = load_seq(seq_fn, exact_trajectories=False)
print("loading phantom")
# phantom = load_phantom(4, (72, 87, 1))  # this is using the phantomlib (running on the server)
phantom = load_phantom_from_nifti(nifit_json_fn)  # this is using python to convert a local nifti
print("running mr0 simulation")
signal_mr0 = _to_complex_np(sim_mr0(seq, phantom))
print("running rapisim simulation")
signal_rapi = _to_complex_np(sim_spdg(seq, phantom))


n_sig = min(signal_rapi.size, signal_mr0.size)
s1 = signal_rapi[:n_sig]
s2 = signal_mr0[:n_sig]

plt.figure(figsize=(10, 4))
plt.plot(np.abs(s1), label="rapisim |s|")
plt.plot(np.abs(s2), label="mr0sim |s|", alpha=0.85)
plt.xlabel("readout index")
plt.ylabel("|signal|")
plt.title("Simulated signal magnitude")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()